development:
  SECRET_KEY: ACUcfZ6C1XpBJCRP
  USER_API_SITE: http://dev.2010.mindpin.com
  IMAGE_CACHE_SITE: http://192.168.1.8:5885
  ATTACHED_FILE_PATH_ROOT: /root/mindpin_base/mindpin_education_files/
  ATTACHED_FILE_URL_ROOT: http://img.edu.mindpin.com/

  APP_PREFIX: app/mindmap_editor_cheng
  API_SITE: http://dev.2010.mindpin.com
  THIS_SITE: http://192.168.1.8:1661

test:
  SECRET_KEY: ACUcfZ6C1XpBJCRP
  USER_API_SITE: http://192.168.1.8:5115
  IMAGE_CACHE_SITE: http://192.168.1.8:9530
  ATTACHED_FILE_PATH_ROOT: /root/mindpin_base/mindpin_education_files/
  ATTACHED_FILE_URL_ROOT: http://img.edu.mindpin.com/

  APP_PREFIX: app/mindmap_editor_cheng
  API_SITE: http://192.168.1.8:3007
  THIS_SITE: http://192.168.1.8:1661

production:
  SECRET_KEY: RlwcuvxHvBQqr87Y
  USER_API_SITE: http://userapi.mindpin.com
  IMAGE_CACHE_SITE: http://mindmapimagecache.mindpin.com
  ATTACHED_FILE_PATH_ROOT: /web/apps/mindpin_mm_images/
  ATTACHED_FILE_URL_ROOT: http://img1.mindpin.com/

  APP_PREFIX: app/mindmap_editor
  API_SITE: http://www.mindpin.com
  THIS_SITE: http://mm2010.mindpin.com
