test:
  ttl: 604800
  namespace: mindmap_editor_test_cheng
  sessions: false
  debug: false
  servers: localhost:11211

development:
  ttl: 604800
  namespace: mindmap_editor_development
  sessions: false
  debug: false
  servers: localhost:11211

production:
  ttl: 604800
  namespace: mindmap_editor_production
  sessions: false
  debug: false
  servers: localhost:11211